name: "Trigger workflow"
description: "Trigger another workflow with github api"

inputs:
  repo-org:
    required: true
    description: "organization of GitHub"
    default: "nxz-group"
  repo-name:
    required: true
    description: "Target repository of github"
  event-type:
    required: true
    description: "Event type"
    default: "trigger-workflow"
  service-name:
    required: true
    description: "Name of application service"
  image-tag:
    required: true
    description: "Tag version of application service"
  github-token:
    required: true
    description: "GitHub token"
runs:
  using: composite   
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Trigger Workflow in Another Repository
      shell: bash
      run: |
        # Set the required variables
        repo_owner="${{ inputs.repo-org }}"
        repo_name="${{ inputs.repo-name }}"
        event_type="${{ inputs.event-type }}"
        service="${{ inputs.service-name }}"
        image="${{ inputs.image-tag }}"

        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github-token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"image\": \"$image\"}}"