name: "Commitlint"
description: "Commitlint"

inputs:
  enable-commitlint:
    required: false
    description: 'control enable or disable commitlint'
    default: 'true'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Validate current commit (last commit) with commitlint
      if: ${{ inputs.enable-commitlint == 'true' }} 
      shell: bash
      run: npx commitlint --from HEAD~1 --to HEAD --verbose
     
