name: "Pylint"
description: "Action for lint python with pylint"

inputs:
  python-directory:
    required: true
    description: "directorie for validate pylint"
  requirements:
    required: true
    description: "Path of requirements.txt"
    default: requirements.txt
  ignore:
    description: "Ignore path for pylint"
    default: 'venv'
runs:
  using: composite   
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create and activate venv
      shell: bash
      run: |
        python3 -m venv venv

    - name: Install dependencies
      shell: bash
      run: |
        source venv/bin/activate
        pip3 install -r ${{ inputs.requirements }}

    - name: Pylint
      shell: bash
      run: |
        source venv/bin/activate
        pylint --recursive=y --ignore=${{ inputs.ignore }} ${{ inputs.python-directory }}