name: Push image
description: build and push image to ECR
inputs:
  image-name:
     description: "image full name"
     required: true
  region:
    description: "specific region to use"
    default: me-central-1
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Push image to ECR
      shell: bash
      env:
        IMAGE: ${{ inputs.image-name }}
      run: |
        docker push $IMAGE
        echo "Push image succes $IMAGE"