name: Python Validate

on:
  workflow_call:
    inputs:
      python-directory:
        description: "directorie for validate python"
        type: string
      requirements:
        description: "path of requirements.txt"
        type: string
      label-runner:
        description: "label for select runner develop or production"
        type: string
        default: develop
      pylint-enable:
        type: boolean
        default: true
      black-enable:
        type: boolean
        default: true
      pytest-enable:
        type: boolean
        default: true

jobs:
  start:
    name: Start
    runs-on: ${{ inputs.label-runner }}
    steps:
    - name: echo enable status
      run: |
        echo "pylint-enable: ${{ inputs.pylint-enable }}"
        echo "black-enable: ${{ inputs.black-enable }}"

  pylint:
    if: ${{ inputs.pylint-enable }}
    name: Pylint
    runs-on: ${{ inputs.label-runner }}
    steps:
      - name: Pylint
        uses: nxz-group/github-shared-workflows/.github/actions/python-lint@main
        with:
          python-directory: ${{ inputs.python-directory }}
          requirements: ${{ inputs.requirements }}

  black-format:
    if: ${{ inputs.black-enable }}
    name: Black format
    runs-on: ${{ inputs.label-runner }}
    steps:
      - name: Black
        uses: nxz-group/github-shared-workflows/.github/actions/python-format@main
        with:
          python-directory: ${{ inputs.python-directory }}
          requirements: ${{ inputs.requirements }}

  pytest:
    if: ${{ inputs.pytest-enable }}
    name: Pytest
    runs-on: ${{ inputs.label-runner }}
    steps:
      - name: Pytest
        uses: nxz-group/github-shared-workflows/.github/actions/python-test@main
        with:
          python-directory: ${{ inputs.python-directory }}
          requirements: ${{ inputs.requirements }}