name: "Pylint"
description: "Action for check format python with black"

inputs:
  python-directory:
    required: true
    description: "directorie for check format"
  requirements:
    required: true
    description: "Path of requirements.txt"
    default: requirements.txt

runs:
  using: composite   
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create and activate venv
      shell: bash
      run: |
        python3 -m venv venv

    - name: Install dependencies
      shell: bash
      run: |
        source venv/bin/activate
        pip3 install -r ${{ inputs.requirements }}

    - name: Black format
      shell: bash
      run: |
        source venv/bin/activate
        black --check --verbose ${{ inputs.python-directory }}