name: Build image
description: build docker image
inputs:
  image-name:
    description: "image full name registryid/repo:tag"
    required: true
  ecr-repository:
    description: "ECR repository name"
    required: true
  dockerfile-path:
    description: "path for select dockerfile"
    default: ./Dockerfile
    required: false
  region:
    description: "specific region to use"
    default: me-central-1
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Build tag
      shell: bash
      run: docker build -f ${{ inputs.dockerfile-path }} -t ${{ inputs.image-name }} .