name: "Validate Java"
description: "Action for validate for Java"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    ## test-gihub-app/github-workflow-template
    - uses: ././.github/actions/hello
     
