name: "Validate Java"
description: "Action for validate for Java"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: test-gihub-app/github-workflow-template/.github/actions/hello
     
