name: update-image-tag
description: "Action for update image tag"

inputs:
  argocd-repo:
    description: "The repository of ArgoCD"
    required: true
  image-tag:
    description: "The tag of image"
    required: true
  argocd-configs-path:
    description: "The config path of ArgoCD"
    required: true
  environment:
    description: "The environment to deploy"
    required: true
  key-edit:
    description: "The key to edit"
    default: .image.tag
    required: false
  github-token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout ${{ inputs.argocd-repo }} reposiory
      uses: actions/checkout@v4
      with:
        repository: nxz-group/${{ inputs.argocd-repo }}
        token: ${{ inputs.github-token }}
        path: ./${{ inputs.argocd-repo }} 

    - name: Create branch PR
      shell: bash
      working-directory: ${{ inputs.argocd-repo }} 
      run: |
        git pull
        git checkout -b "${{ inputs.argocd-configs-path }}/${{ inputs.image-tag }}"
        git push --set-upstream origin ${{ inputs.argocd-configs-path }}/${{ inputs.image-tag }}

    - name: Update image tag
      shell: bash
      env: 
        CONFIGS_PATH: ${{ inputs.argocd-configs-path }}/values-ae-${{ inputs.environment }}.yaml
      working-directory: ${{ inputs.argocd-repo }} 
      run: |
        yq -i '${{ inputs.key-edit }} = "${{ inputs.image-tag }}"' "$CONFIGS_PATH"
        yq -i '.labels."app.kubernetes.io/version" = "${{ inputs.image-tag }}"' "$CONFIGS_PATH"

    - name: Get Service name
      shell: bash
      id: get_service
      run: |
        argocd_path=${{ inputs.argocd-configs-path }}
        base_name=$(basename "$argocd_path")
        echo "service=$base_name" >> $GITHUB_OUTPUT 

    - name: Commit and push changes
      shell: bash
      working-directory: ${{ inputs.argocd-repo }} 
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -am "feat: update image tag of ${{ steps.get_service.outputs.service }} to ${{ inputs.image-tag }}"
        git push
      
    - name: Create pull request
      shell: bash
      working-directory: ${{ inputs.argocd-repo }} 
      run: |
        gh pr create  --head nxz-group:${{ inputs.argocd-configs-path }}/${{ inputs.image-tag }} --base main --fill
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Merge pull request
      if: ${{ inputs.environment != 'prd' }} 
      shell: bash
      working-directory: ${{ inputs.argocd-repo }} 
      run: |
        gh pr merge --merge --delete-branch
      env:
        GH_TOKEN: ${{ inputs.github-token }}