name: "Sonarqube"
description: "This workflow checks out the code, installs dependencies, runs coverage, performs a SonarQube scan, and checks the SonarQube quality gate status."

inputs:
  sonar_host_url:
    required: true
    description: "The SonarQube server URL"
  sonar_token:
    required: true
    description: "The authentication token for SonarQube"
  node_version:
    description: "NodeJs version"
    default: '18'
  enforce_quality_gate:
    description: "Enforce quality gate"
    default: 'false'
runs:
  using: composite   
  steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Install dependency
        uses: nxz-group/github-shared-workflows/.github/actions/install-dependency@main
        with:
          node-version: ${{ inputs.node_version }}

      - name: Run coverage
        run: npm run coverage
        shell: bash
        continue-on-error: true

      - name: SonarQube Scan
        uses: nxz-group/sonarqube-scan-action@main
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
          SONAR_HOST_URL: ${{ inputs.sonar_host_url }}

      - name: SonarQube Quality Gate check
        if: inputs.enforce_quality_gate == 'true'
        uses: nxz-group/sonarqube-quality-gate-action@main
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
          SONAR_HOST_URL: ${{ inputs.sonar_host_url }}

  