name: "grafana faro config"
description: "Grafana faro config"

inputs:
  grafana-api-key:
    required: true
    description: "Grafana faro Api key"
  grafana-domain:
    required: true
    description: "Grafana faro Domain"
  source-config-path:
    required: true
    description: "Source config path"
  target-config-path:
    required: true
    description: "Traget config path"
    default: 'public/local/config.js'

runs:
  using: composite
  steps:
    - name: Replace Grafana ENV
      shell: bash
      run: |
        key_api_key="REACT_APP_GRAFANA_API_KEY"
        key_domain="REACT_APP_GRAFANA_DOMAIN"

        value_api_key=${{ inputs.grafana-api-key }}
        value_domain=${{ inputs.grafana-domain }}

        sed -i~ "s|^$key_api_key=.*|$key_api_key=$value_api_key|" .env 
        sed -i~ "s|^$key_domain=.*|$key_domain=$value_domain|" .env

    - name: Copy config file
      shell: bash
      run: cp ${{ inputs.source-config-path }} ${{ inputs.target-config-path }}