name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: test-gihub-app/github-workflow-template/.github/workflow-templates/echo-template.yaml@main