name: Java Validate

on:
  push:

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ././.github/actions/action-test