name: Java Validate

on:
  push:
  workflow_call:
    inputs:
      ref-name:
        default: ${{ github.ref_name }}
        type: string
        description: "The label of the runner to execute the workflow"

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: test-gihub-app/github-workflow-template/.github/actions/action-test