name: Java Validate

on:
  push:

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:

    - name: echo enable status
      run: echo hello

    - uses: ././.github/actions/action-test