name: Publish version on Lambda Function

on:
  workflow_call:
    inputs:
      lambda-name:
        required: true
        type: string
      label-runner:
        description: "label for select runner develop or production"
        type: string
        default: develop
    outputs:
      publish-version:
        description: "version from lambda publish version"
        value: ${{ jobs.publish-version.outputs.publish_version }}

jobs:
  publish-version:
    name: Publish version on Lambda Function
    runs-on: 
      - self-hosted
      - ${{ inputs.label-runner }}
    outputs:
      publish_version: ${{ steps.publish-version.outputs.PUBLISH_VERSION }}
    env:
      LAMBDA_NAME: ${{ inputs.lambda-name }}
    steps:
      - name: Publish Version
        id: publish-version
        run: |
          LAMBDA_PUBLISH=$(aws lambda publish-version --function-name $LAMBDA_NAME)
          echo $LAMBDA_PUBLISH
          PUBLISH_VERSION=$(echo $LAMBDA_PUBLISH | jq -r .Version)
          echo $PUBLISH_VERSION
          echo "PUBLISH_VERSION=$PUBLISH_VERSION" >> $GITHUB_OUTPUT