name: Java Validate

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        description: "The version of Java"
        type: string
      maven-version:
        required: true
        description: "The version of maven"
        type: string
      label-runner:
        description: "label for select runner develop or production"
        type: string
        default: develop
      java-format-enable:
        type: boolean
        default: true
        description: "Enable or disable the Java code format check."
      unit-test-enable:
        type: boolean
        default: true
        description: "Enable or disable the execution of unit tests."
      code-quality-enable:
        type: boolean
        default: false
        description: "Enable or disable the code quality analysis using SonarQube."
      sonar_host_url:
        type: string
        required: false
        description: "The sonarqube host url"
        default: "https://sonarqube.nonprd.oceanxz-platform.com"
      container-sonarqube:
        type: string
        required: true
        description: "Container sonarqube"
        default: 654654479736.dkr.ecr.me-central-1.amazonaws.com/sonarqube-scan-action:10.0-ubuntu-24.04-3
    secrets:
      sonar_token:
        required: true
        description: "The sonarqube token"

jobs:
  start:
    name: Start
    runs-on: ${{ inputs.label-runner }}
    steps:
    - name: echo enable status
      run: |
        echo "java-format-enable: ${{ inputs.java-format-enable }}"
        echo "unit-test-enable: ${{ inputs.unit-test-enable }}"

  unit-test:
    if: ${{ inputs.unit-test-enable }}
    name: Unit Test
    runs-on: ${{ inputs.label-runner }}
    steps:
    - name: Run Unit Test
      uses: nxz-group/github-shared-workflows/.github/actions/unit-test-java@main
      with:
        java-version: ${{ inputs.java-version }}
        maven-version: ${{ inputs.maven-version }}

  java-format:
    if: ${{ inputs.java-format-enable }}
    name: Java Format
    runs-on: ${{ inputs.label-runner }}
    steps:
    - name: Check Format Java
      uses: nxz-group/github-shared-workflows/.github/actions/check-format-java@main
      with:
        java-version: ${{ inputs.java-version }}
        maven-version: ${{ inputs.maven-version }}

  code-quality:
    if: ${{ inputs.code-quality-enable }}
    name: Code Quality
    runs-on: ${{ inputs.label-runner }}
    container:
      image: ${{ inputs.container-sonarqube }}
    steps:
      - name: Sonarqube scaner
        uses: nxz-group/github-shared-workflows/.github/actions/sonarqube-java@main
        with:
          sonar_host_url: ${{ inputs.sonar_host_url }}
          sonar_token: ${{ secrets.sonar_token }}