name: JS Validate

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        description: "The version of maven"
        type: string
      label-runner:
        description: "label for select runner develop or production"
        type: string
        default: develop
      code-quality-enable:
        type: boolean
        default: true
      sonar_host_url:
        type: string
        required: false
        description: "The sonarqube host url"
        default: "https://sonarqube.nonprd.oceanxz-platform.com"
    secrets:
      sonar_token:
        required: true
        description: "The sonarqube token"

jobs:
  code-quality:
    if: ${{ inputs.code-quality-enable }}
    name: Code Quality
    runs-on: ${{ inputs.label-runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: sonarqube scanner
        uses: nxz-group/github-shared-workflows/.github/actions/sonarqube@main
        continue-on-error: true
        with:
          sonar_host_url: ${{ inputs.sonar_host_url }}
          sonar_token: ${{ secrets.sonar_token }}