name: Add permission on Lambda Function

on:
  workflow_call:
    inputs:
      label-runner:
        description: "label for select runner develop or production"
        type: string
        default: develop
      lambda-name:
        required: true
        type: string
      lambda-publish-version:
        required: true
        type: string
      statement-id:
        required: false
        type: string
        default: api-gateway-${{ github.run_id }}-${{ github.run_attempt }}
      source-arn:
        required: true
        type: string

jobs:
  add-permission:
    name: Add permission on Lambda Function
    runs-on: 
      - self-hosted
      - ${{ inputs.label-runner }}
    env:
      LAMBDA_NAME: ${{ inputs.lambda-name }}
      PUBLISH_VERSION: ${{ inputs.lambda-publish-version }}
      SOURCE_ARN: ${{ inputs.source-arn }}
    steps:
      - name: Add permission on Lambda Function
        id: add-permission-lambda
        run: |
          aws lambda add-permission --function-name ${{ env.LAMBDA_NAME }}:${{ env.PUBLISH_VERSION }} \
          --action lambda:InvokeFunction \
          --statement-id ${{ inputs.statement-id }} \
          --principal apigateway.amazonaws.com \
          --source-arn '${{ env.SOURCE_ARN }}'