name: "Unit Test Java"
description: "Action for Unit Test for Java"

inputs:
  java-version:
    required: true
    description: "The version of Java"
  maven-version:
    required: true
    description: "The version of maven"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@main
      with:
        java-version: ${{ inputs.java-version }}
        maven-version: ${{ inputs.maven-version }}
    - name: Run Unit Test
      shell: bash
      run: mvn test 