name: "Argocd sync and wait"
description: "Argocd cli sync and wait application"

inputs:
  hostname:
    required: true
    description: "ArgoCD hostname"
  username:
    required: true
    description: "ArgoCD username"
  password:
    required: true
    description: "ArgoCD password"
  app-name:
    required: true
    description: "Name of argocd application"
  sync-status:
    description: "argocd sync enable/disable"
    default: "true"
  wait-status:
    description: "argocd wait enable/disable"
    default: "true"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login ArgoCD
      shell: bash
      run: |
        argocd login ${{ inputs.hostname }} --username ${{ inputs.username }} --password ${{ inputs.password }}

    - name: Argocd sync app
      if: inputs.sync-status == 'true'
      shell: bash
      run: argocd app sync ${{ inputs.app-name }} --grpc-web

    - name: Argocd wait app
      if: inputs.wait-status == 'true'
      shell: bash
      run: argocd app wait ${{ inputs.app-name }} --grpc-web